# Файл docker-compose должен начинаться с тега версии.
# Мы используем "3" так как это - самая свежая версия на момент написания этого кода.
version: '3'


# Следует учитывать, что docker-composes работает с сервисами.
# 1 сервис = 1 контейнер.
# Сервисом может быть клиент, сервер, сервер баз данных...
# Раздел, в котором будут описаны сервисы, начинается с 'services'.
services:
  db:
    image: mysql:latest
    container_name: db
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - ./databases:/docker-entrypoint-initdb.d
      - db_volume:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=password


  pr1:
    build: .
    ports:
      - "80:80"
    volumes:
      - ./src/html/db:/var/www/html
    links:
      - db

  pr2:
    build: .
    ports:
      - "80:80"
    volumes:
      - ./src/html/pr2:/var/www/html

volumes:
  db_volume:

