version: '3'

services:
  nginx:
    image: nginx:latest
    container_name: proxy
    volumes:
      - ./src/html:/data/www/html
      - ./cfg/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "80:80"

  apache:
    container_name: server
    image: php:8.0-apache
    volumes:
      - ./src/html:/var/www/html
